version: '3.8'
services:
  php:
    image: 3lever/php:8.1.7-cli-postgresql-dev
    ports:
      - "${HTTP_PORT:-8003}:8003"
    volumes:
      - ./:/app
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db-database
    volumes:
      - .docker/database/data:/var/lib/postgresql/data
    ports:
      - 5434:5432
