version: '3.8'
services:
  web:
    image: nginx:1.17
    volumes:
      - ./:/app
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8003:80"
    links:
      - php

  php:
    image: 3lever/php:8.1.7-fpm-postgresql-dev
    volumes:
      - ./:/app
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db-database
    volumes:
      - .docker/database/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
