name: Continuous Integration

on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: 3lever/php:8.1.7-fpm-postgresql-dev
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: db-user
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            ./vendor
            ./public
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/symfony.lock') }}-
            ${{ runner.os }}-build-
      - name: Composer
        run: composer dev

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_ENV: test
    container:
      image: 3lever/php:8.1.7-fpm-postgresql-dev
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: db-user
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/symfony.lock') }}-${{ hashFiles('**/composer.lock') }}
          path: |
            ./vendor
            ./public
      - name: Setup Database
        run: composer db

      - name: Fixtures
        run: composer db:fixtures

      - name: Validate Data base
        run: bin/console doctrine:schema:validate

      - name: Run Tests
        run: composer test